# Copyright (C) 2026
# Author: Abhinav S <abhinavsasivala02@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#!/usr/bin/env python3
"""
gen_zeta_table.py
=================
Generates the 256 NTT zeta (twiddle-factor) values for FIPS 204 ML-DSA.

Algorithm
---------
  - q    = 8_380_417  (prime modulus)
  - zeta = 1753       (primitive 512th root-of-unity mod q)
  - R    = 2^32 mod q (Montgomery constant)
  - For k in 0..255:
        zeta_mont[k] = zeta^{BitRev8(k)} * R  mod q

Outputs
-------
  rtl/pkg/zeta_rom.vh   -- Verilog `include file with localparam array
  rtl/pkg/zeta_rom.hex  -- one 6-digit hex word per line for $readmemh

Run once before simulation or synthesis:
  python scripts/gen_zeta_table.py
"""

import os, sys

Q    = 8_380_417          # FIPS 204 prime modulus
N    = 256                # polynomial degree
ZETA = 1753               # primitive 512th root-of-unity mod Q

# Montgomery constant R = 2^32 mod Q
R    = pow(2, 32, Q)      # = 4_193_792
R2   = pow(2, 64, Q)      # = 2^64 mod Q  (used to convert TO Montgomery form)
QINV = pow(Q, -1, 2**32)  # Q^{-1} mod 2^32  (for Montgomery reduction)

# ---- helper ----------------------------------------------------------------
def brv8(k: int) -> int:
    """Bit-reverse the 8-bit integer k."""
    result = 0
    for i in range(8):
        if k & (1 << i):
            result |= (1 << (7 - i))
    return result

# ---- compute table ---------------------------------------------------------
zetas = []
for k in range(N):
    exp   = brv8(k)
    z     = pow(ZETA, exp, Q)   # zeta^{brv(k)} mod Q
    z_m   = (z * R) % Q        # Montgomery form (always positive)
    zetas.append(z_m)

# ---- sanity checks ---------------------------------------------------------
assert zetas[0] == R % Q,          f"zetas[0] mismatch: {zetas[0]} vs {R%Q}"
assert zetas[1] == 25847,          f"zetas[1] mismatch: {zetas[1]}"   # known ref value

# ---- output ----------------------------------------------------------------
out_dir = os.path.join(os.path.dirname(__file__), '..', 'rtl', 'pkg')
os.makedirs(out_dir, exist_ok=True)

vh_path  = os.path.join(out_dir, 'zeta_rom.vh')
hex_path = os.path.join(out_dir, 'zeta_rom.hex')

with open(vh_path, 'w') as f:
    f.write("// ==========================================================\n")
    f.write("// AUTO-GENERATED by scripts/gen_zeta_table.py  -- DO NOT EDIT\n")
    f.write(f"// FIPS 204 ML-DSA NTT Zeta Table  (Montgomery form, R=2^32)\n")
    f.write(f"// Q={Q}  ZETA={ZETA}  R mod Q = {R}  R^2 mod Q = {R2}\n")
    f.write("// ==========================================================\n\n")
    f.write("localparam logic [23:0] ZETA_ROM [0:255] = '{\n")
    for i, z in enumerate(zetas):
        comma = "," if i < 255 else " "
        exp   = brv8(i)
        f.write(f"  24'h{z:06X}{comma} // [{i:3d}] zeta^{exp}\n")
    f.write("};\n")

with open(hex_path, 'w') as f:
    for z in zetas:
        f.write(f"{z:06X}\n")

print(f"[gen_zeta_table] Q={Q}  R={R}  R2={R2}  QINV={QINV}")
print(f"[gen_zeta_table] zetas[0] = {zetas[0]}  (R mod Q)")
print(f"[gen_zeta_table] zetas[1] = {zetas[1]}  (expect 25847)")
print(f"[gen_zeta_table] Wrote {vh_path}")
print(f"[gen_zeta_table] Wrote {hex_path}")
