# Copyright (C) 2026
# Author: Abhinav S <abhinavsasivala02@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#!/usr/bin/env python3
# Generate ML-DSA-65 signing KAT vectors for the RTL testbench.
#
# For each of the 5 seeds used in tb/mldsa65_kat_vectors.vh (xi =
# 0x20*i..0x20*i+0x1f), this script:
#   1. runs keypair(xi)       -> sk (also populates sk_ram in HW via keygen)
#   2. picks a fixed rnd/msg
#   3. computes mu = H(tr + 0x0000 + msg)
#   4. computes sign(sk, msg, rnd) -> expected sig and kappa
# and emits:
#   - tb/mldsa65_sign_vectors.vh     (KATx_RND / KATx_MU / KATx_KAPPA)
#   - expected/sig_<i>.hex            (sig bytes as 32-bit LE words, 828 words,
#                                      matching the tb_mldsa_sign_kat dump)
#
# The expected .hex words are int.from_bytes(sig[4*i:4*i+4], 'little')
# because the AXI read packs RDATA = {ram[+3],ram[+2],ram[+1],ram[+0]}.

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mldsa_ref import (keypair, sign, H, SIG_BYTES, RNDBYTES, TRBYTES)

NUM_VEC = 5
EXPECTED_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'expected')
TB_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'tb')


def make_xi(i):
    return bytes(range(0x20 * i, 0x20 * i + 0x20))


def make_rnd(i):
    # Distinct, deterministic 32-byte random-looking values per vector.
    base = 0xA0 + 0x20 * i
    return bytes((base + j) % 256 for j in range(32))


def make_msg(i):
    return b'ML-DSA-65 signing KAT vector %d' % i


def main():
    os.makedirs(EXPECTED_DIR, exist_ok=True)

    lines = []
    lines.append('// =============================================================================')
    lines.append('// mldsa65_sign_vectors.vh - Generated by scripts/gen_sign_vectors.py')
    lines.append('//')
    lines.append('// Per-vector signing inputs for tb_mldsa_sign_kat.v: rnd and mu, plus the')
    lines.append('// expected rejection-loop kappa for cross-checking. mu is the full 64-byte')
    lines.append('// message digest mu = H(tr || 0x0000 || msg) from scripts/mldsa_ref.py.')
    lines.append('// =============================================================================')
    lines.append('')

    for i in range(NUM_VEC):
        xi = make_xi(i)
        pk, sk, tr = keypair(xi)
        rnd = make_rnd(i)
        msg = make_msg(i)
        sig, mu, kappa = sign(sk, msg, rnd)

        assert len(mu) == 64, 'mu length'
        assert len(sig) == SIG_BYTES, 'sig length'

        # mu as 512-bit little-endian int (matches mu_w bit ordering)
        mu_int = int.from_bytes(mu, 'little')
        rnd_int = int.from_bytes(rnd, 'little')

        lines.append('// KAT Vector %d: xi=0x%064x, rnd=%s, msg=%r' % (
            i, int.from_bytes(xi, 'little'), rnd.hex(), msg))
        lines.append('localparam [255:0] KAT%d_RND   = 256\'h%064x;' % (i, rnd_int))
        lines.append('localparam [511:0] KAT%d_MU    = 512\'h%0128x;' % (i, mu_int))
        lines.append('localparam [15:0]  KAT%d_KAPPA = 16\'d%d;' % (i, kappa))
        lines.append('')

        # Expected signature hex (828 32-bit LE words)
        with open(os.path.join(EXPECTED_DIR, 'sig_%d.hex' % i), 'w') as f:
            for w in range(828):
                chunk = sig[4 * w:4 * w + 4]
                if len(chunk) < 4:
                    chunk = chunk + bytes(4 - len(chunk))
                f.write('%08x\n' % int.from_bytes(chunk, 'little'))

        print('vec %d: kappa=%d sig[0:8]=%s' % (
            i, kappa, sig[:8].hex()))

    lines.append('`define NUM_SIGN_VECTORS %d' % NUM_VEC)
    lines.append('')

    with open(os.path.join(TB_DIR, 'mldsa65_sign_vectors.vh'), 'w') as f:
        f.write('\n'.join(lines))

    print('Wrote tb/mldsa65_sign_vectors.vh and expected/sig_*.hex')


if __name__ == '__main__':
    main()
