# Copyright (C) 2026
# Author: Abhinav S <abhinavsasivala02@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
#!/usr/bin/env python3
# gen_nist_vectors.py - Emit RTL KAT vectors from the official NIST .rsp file.
#
# The NIST PQCsignKAT_4032.rsp cases use a 48-byte AES-CTR DRBG seed. The
# reference derives, in order:
#     xi  = DRBG(SKBYTES)   -> keypair(xi)
#     rnd = DRBG(RNDBYTES)  -> sign(sk, msg, rnd)
#     sm  = sig + msg
#
# We replay the DRBG to recover xi/rnd, compute mu, and emit a per-case pack
# (one .mem set per case) so the RTL KAT can be driven end-to-end with the
# SAME inputs NIST used, and compared byte-exact against NIST's pk/sk/sm.
#
# Emits (into sim/tb/nist/):
#   <i>/xi_<i>.mem  pk_<i>.mem  sk_<i>.mem  rnd_<i>.mem  mu_<i>.mem  sig_<i>.mem
# plus nist_vectors.vh (per-case KAPPA, and file list).
#
# Reference check: run  python scripts/mldsa_ref.py constraints/PQCsignKAT_4032.rsp 100
# (100/100 must pass before using these vectors).
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mldsa_ref import (parse_rsp, DRBG, keypair, sign, H,
                       SEEDBYTES, RNDBYTES, TRBYTES, SIG_BYTES)

RSP   = r'constraints/PQCsignKAT_4032.rsp'
OUT   = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'sim', 'tb', 'nist')
NUM   = 100


def write_mem(path, data):
    with open(path, 'w') as f:
        for b in data:
            f.write('%02x\n' % b)


def main():
    from Crypto.Cipher import AES
    vecs = parse_rsp(RSP)
    os.makedirs(OUT, exist_ok=True)
    vh_lines = ['// nist_vectors.vh - generated by scripts/gen_nist_vectors.py',
                '`define NIST_NUM_VECTORS %d' % NUM, '']

    bad = 0
    for v in vecs[:NUM]:
        i = v['count']
        seed48 = v['seed']
        msg = v['msg']
        drbg = DRBG(seed48, AES)
        xi = drbg.randombytes(SEEDBYTES)
        pk, sk, tr = keypair(xi)
        rnd = drbg.randombytes(RNDBYTES)
        sig, mu, kappa = sign(sk, msg, rnd)
        sm = sig + msg

        # sanity vs NIST ground truth
        ok = (pk == v['pk']) and (sk == v['sk']) and (sm == v['sm'])
        if not ok:
            bad += 1
            print('count=%d: MISMATCH vs NIST' % i)
            continue

        d = os.path.join(OUT, str(i))
        os.makedirs(d, exist_ok=True)
        write_mem(os.path.join(d, 'xi_%d.mem' % i), xi)
        write_mem(os.path.join(d, 'pk_%d.mem' % i), pk)
        write_mem(os.path.join(d, 'sk_%d.mem' % i), sk)
        write_mem(os.path.join(d, 'rnd_%d.mem' % i), rnd)
        write_mem(os.path.join(d, 'mu_%d.mem' % i), mu)
        write_mem(os.path.join(d, 'sig_%d.mem' % i), sig)
        vh_lines.append('`define NIST%d_KAPPA %d' % (i, kappa))

    if bad:
        print('ERROR: %d cases failed NIST comparison' % bad)
        sys.exit(1)

    with open(os.path.join(OUT, 'nist_vectors.vh'), 'w') as f:
        f.write('\n'.join(vh_lines) + '\n')

    print('Wrote %d NIST-derived vectors to %s (all matched NIST ground truth).'
          % (NUM, OUT))


if __name__ == '__main__':
    main()
