// =============================================================================
// mldsa65_sign_vectors.vh - Generated by scripts/gen_sign_vectors.py
//
// Per-vector signing inputs for tb_mldsa_sign_kat.v: rnd and mu, plus the
// expected rejection-loop kappa for cross-checking. mu is the full 64-byte
// message digest mu = H(tr || 0x0000 || msg) from scripts/mldsa_ref.py.
// =============================================================================

// KAT Vector 0: xi=0x1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100, rnd=a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf, msg=b'ML-DSA-65 signing KAT vector 0'
localparam [255:0] KAT0_RND   = 256'hbfbebdbcbbbab9b8b7b6b5b4b3b2b1b0afaeadacabaaa9a8a7a6a5a4a3a2a1a0;
localparam [511:0] KAT0_MU    = 512'h7444661019fb7e3a3148996c2522c72671f735fae19804949edeb3f2b99af02e13bcec0b7f93c5536455d0f07d9e35a5e09751f9001f1957683adb36fc54e4c0;
localparam [15:0]  KAT0_KAPPA = 16'd15;

// KAT Vector 1: xi=0x3f3e3d3c3b3a393837363534333231302f2e2d2c2b2a29282726252423222120, rnd=c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf, msg=b'ML-DSA-65 signing KAT vector 1'
localparam [255:0] KAT1_RND   = 256'hdfdedddcdbdad9d8d7d6d5d4d3d2d1d0cfcecdcccbcac9c8c7c6c5c4c3c2c1c0;
localparam [511:0] KAT1_MU    = 512'h4d9e04756fdd0470e254355e15e01adf111b7dc161ce81066b997beb6c5c8abf8f859ce3516785584b89edda5f07f5de24f0672a87395c8f68b9f65bf3a2ec24;
localparam [15:0]  KAT1_KAPPA = 16'd25;

// KAT Vector 2: xi=0x5f5e5d5c5b5a595857565554535251504f4e4d4c4b4a49484746454443424140, rnd=e0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff, msg=b'ML-DSA-65 signing KAT vector 2'
localparam [255:0] KAT2_RND   = 256'hfffefdfcfbfaf9f8f7f6f5f4f3f2f1f0efeeedecebeae9e8e7e6e5e4e3e2e1e0;
localparam [511:0] KAT2_MU    = 512'h9e325cf5a20f0d0a9f7141dfbb856ed7fddb1486566cd51afae13fd70fced2aa3279d886d5c00f05d4a60e7b7a3dc0d2c14f0383c7acdaa917a674c2d60f1fc7;
localparam [15:0]  KAT2_KAPPA = 16'd45;

// KAT Vector 3: xi=0x7f7e7d7c7b7a797877767574737271706f6e6d6c6b6a69686766656463626160, rnd=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f, msg=b'ML-DSA-65 signing KAT vector 3'
localparam [255:0] KAT3_RND   = 256'h1f1e1d1c1b1a191817161514131211100f0e0d0c0b0a09080706050403020100;
localparam [511:0] KAT3_MU    = 512'h71d4eb6dca5105df52ec9b837a95d1e2dfed83e02b8104eb16902d6d5c05fce2b676ddf8cfc82501651f24a698dd88650b361f4e9d26858cd2e56aa9c9e011ab;
localparam [15:0]  KAT3_KAPPA = 16'd60;

// KAT Vector 4: xi=0x9f9e9d9c9b9a999897969594939291908f8e8d8c8b8a89888786858483828180, rnd=202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f, msg=b'ML-DSA-65 signing KAT vector 4'
localparam [255:0] KAT4_RND   = 256'h3f3e3d3c3b3a393837363534333231302f2e2d2c2b2a29282726252423222120;
localparam [511:0] KAT4_MU    = 512'h6b8362aa30b91fcbecb2405fc23ff23a9689ac3ca3422c63e8b015744f4d227529478a47e63843f35c186b1f0f0ee6d2924484fcddbf8d2847df9d66e28dbf38;
localparam [15:0]  KAT4_KAPPA = 16'd0;

`define NUM_SIGN_VECTORS 5
